### ISSUE TITLE
Occasional failure to migrate ietfdb/datatracker SVN

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/svn-github-convert#58]
https://github.com/ietf-ribose/svn-github-convert/runs/4677194127?check_suite_focus=true
```
2022-01-01T03:31:02.2298693Z Progress: [=============================                     ] 59.40% -
2022-01-01T03:31:02.4351155Z Progress: [=============================                     ] 59.40% \
2022-01-01T03:33:12.6435647Z svn: E170013: Unable to connect to a repository at URL 'https://svn.ietf.org/svn/tools/ietfdb'
2022-01-01T03:33:12.6436747Z svn: E000110: Error running context: Connection timed out
2022-01-01T03:33:12.6454976Z /var/lib/gems/2.7.0/gems/tractive-1.0.11/lib/tractive/revmap_generator.rb:94:in `load': invalid format, document not terminated at line 3, column 3 [parse.c:555] (Ox::ParseError)
2022-01-01T03:33:12.6456874Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/lib/tractive/revmap_generator.rb:94:in `commit_message_from_svn'
2022-01-01T03:33:12.6458417Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/lib/tractive/revmap_generator.rb:63:in `print_revmap_info'
2022-01-01T03:33:12.6459931Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/lib/tractive/revmap_generator.rb:29:in `block (2 levels) in generate'
2022-01-01T03:33:12.6461416Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/lib/tractive/revmap_generator.rb:23:in `foreach'
2022-01-01T03:33:12.6462844Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/lib/tractive/revmap_generator.rb:23:in `block in generate'
2022-01-01T03:33:12.6464271Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/lib/tractive/revmap_generator.rb:22:in `open'
2022-01-01T03:33:12.6465651Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/lib/tractive/revmap_generator.rb:22:in `generate'
2022-01-01T03:33:12.6467224Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/exe/generate.rb:27:in `revmap'
2022-01-01T03:33:12.6468397Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
2022-01-01T03:33:12.6469579Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
2022-01-01T03:33:12.6470732Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
2022-01-01T03:33:12.6471870Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
2022-01-01T03:33:12.6473031Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
2022-01-01T03:33:12.6474155Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
2022-01-01T03:33:12.6475327Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
2022-01-01T03:33:12.6476483Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
2022-01-01T03:33:12.6477532Z 	from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
2022-01-01T03:33:12.6478706Z 	from /var/lib/gems/2.7.0/gems/tractive-1.0.11/exe/tractive:80:in `<top (required)>'
2022-01-01T03:33:12.6479714Z 	from /usr/local/bin/tractive:23:in `load'
2022-01-01T03:33:12.6480556Z 	from /usr/local/bin/tractive:23:in `<main>'
2022-01-01T03:33:12.6576166Z Progress: [=============================                     ] 59.41% |
2022-01-01T03:33:12.6584956Z ##[error]Process completed with exit code 1.
2022-01-01T03:33:12.6760466Z Post job cleanup.
```

**Comment by HassanAkbar** [comment]
We can do one of the following in this case:
- Retry after a specific interval and exit. For example, we will retry after 5 min and if it still fails then we will terminate.
- Retry a few times with increasing delay and then exit. For example, a retry after 3 mins, 10 mins, and 30 mins successively and if it still fails then we will terminate.
- Keep retrying with a delay until it succeeds.

@ronaldtse What do you suggest we should do?

**Comment by ronaldtse** [comment]
I’m not sure why we need to hit a remote location because it would be slow and unreliable. Is it possible to use a local SVN copy for that?

**Comment by HassanAkbar** [comment]
We only go to the remote server in cases when there are multiple commits by the same user with less than one-second difference.

Downloading each SVN repo completely in Github workflow might increase much more time than just connecting to the remote server for a few commits.

@ronaldtse Let me know what you think about it?

**Comment by ronaldtse** [comment]
> But downloading each SVN repo completely in Github workflow

Don't we have https://github.com/ietf-ribose/trac-svn-db/tree/main/svn that provides us with the full local copy?

**Comment by HassanAkbar** [comment]
@ronaldtse We need to compare the `log messages` for the commits having the same timestamp and to get the svn logs we need to run the `svn log` command and for that.

We need a running SVN server this is a local clone of the server, not the running server itself.

I am not sure if we can setup a server from the mirror or not. I am not sure if I am missing something here ?

**Comment by ronaldtse** [comment]
Maybe during our CI run we can start a Subversion server?
https://tecadmin.net/install-subversion-server-on-ubuntu/
